---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nlb-pool-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eip.alibabacloud.com
  resources:
  - eips
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - nlboperator.alibabacloud.com
  resources:
  - listeners
  - nlbs
  - servergroups
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - nlbpools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - nlbpools/finalizers
  - portallocations/finalizers
  verbs:
  - update
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - nlbpools/status
  - portallocations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nlbpool.alibabacloud.com
  resources:
  - portallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
