---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nlb-pool-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eip.alibabacloud.com
  resources:
  - eips
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - nlboperator.alibabacloud.com
  resources:
  - nlbs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - nlbpool.kruise.io
  resources:
  - nlbpools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlbpool.kruise.io
  resources:
  - nlbpools/status
  verbs:
  - get
  - patch
  - update
