package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ListenerPhase represents the lifecycle phase of a Listener CR.
type ListenerPhase string

const (
	ListenerPending ListenerPhase = "Pending"
	ListenerRunning ListenerPhase = "Running"
	ListenerFailed  ListenerPhase = "Failed"
)

// ListenerSpec defines the desired state of Listener
type ListenerSpec struct {
	Region string `json:"region"`
	// LoadBalancerRef references the NLB CR name in the same namespace.
	LoadBalancerRef string `json:"loadBalancerRef"`
	// ServerGroupRef references the ServerGroup CR name in the same namespace.
	ServerGroupRef string `json:"serverGroupRef"`
	// ListenerPort is the listener front-end port.
	ListenerPort int32 `json:"listenerPort"`
	// ListenerProtocol: TCP | UDP | TCPSSL
	ListenerProtocol string `json:"listenerProtocol"`
}

// ListenerStatus defines the observed state of Listener
type ListenerStatus struct {
	Phase      ListenerPhase `json:"phase,omitempty"`
	ListenerId string        `json:"listenerId,omitempty"`
	Message    string        `json:"message,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Listener is the Schema for the listeners API
type Listener struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ListenerSpec   `json:"spec,omitempty"`
	Status ListenerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ListenerList contains a list of Listener
type ListenerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Listener `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Listener{}, &ListenerList{})
}

// DeepCopyInto copies all fields into out.
func (in *ListenerSpec) DeepCopyInto(out *ListenerSpec) { *out = *in }

// DeepCopy is an autogenerated deepcopy function.
func (in *ListenerSpec) DeepCopy() *ListenerSpec {
	if in == nil {
		return nil
	}
	out := new(ListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *ListenerStatus) DeepCopyInto(out *ListenerStatus) { *out = *in }

// DeepCopy is an autogenerated deepcopy function.
func (in *ListenerStatus) DeepCopy() *ListenerStatus {
	if in == nil {
		return nil
	}
	out := new(ListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *Listener) DeepCopyInto(out *Listener) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function.
func (in *Listener) DeepCopy() *Listener {
	if in == nil {
		return nil
	}
	out := new(Listener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *Listener) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *ListenerList) DeepCopyInto(out *ListenerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		inItems, outItems := &in.Items, &out.Items
		*outItems = make([]Listener, len(*inItems))
		for i := range *inItems {
			(*inItems)[i].DeepCopyInto(&(*outItems)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ListenerList) DeepCopy() *ListenerList {
	if in == nil {
		return nil
	}
	out := new(ListenerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ListenerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
