package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ZoneMapping defines the zone and vSwitch configuration for NLB
type ZoneMapping struct {
	ZoneId       string `json:"zoneId"`
	VSwitchId    string `json:"vSwitchId"`
	AllocationId string `json:"allocationId,omitempty"`
}

// NLBSpec defines the desired state of NLB (simplified for pool operator)
type NLBSpec struct {
	LoadBalancerName string       `json:"loadBalancerName,omitempty"`
	AddressType      string       `json:"addressType"`
	AddressIpVersion string       `json:"addressIpVersion,omitempty"`
	VpcId            string       `json:"vpcId"`
	ZoneMappings     []ZoneMapping `json:"zoneMappings"`
}

// NLBStatus defines the observed state of NLB (simplified for pool operator)
type NLBStatus struct {
	LoadBalancerId     string `json:"loadBalancerId,omitempty"`
	LoadBalancerStatus string `json:"loadBalancerStatus,omitempty"`
	DNSName            string `json:"dnsName,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// NLB is the Schema for the nlbs API
type NLB struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NLBSpec   `json:"spec,omitempty"`
	Status NLBStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NLBList contains a list of NLB
type NLBList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NLB `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NLB{}, &NLBList{})
}

// DeepCopyInto copies all fields into out. In must be non-nil.
func (in *ZoneMapping) DeepCopyInto(out *ZoneMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneMapping.
func (in *ZoneMapping) DeepCopy() *ZoneMapping {
	if in == nil {
		return nil
	}
	out := new(ZoneMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out. In must be non-nil.
func (in *NLBSpec) DeepCopyInto(out *NLBSpec) {
	*out = *in
	if in.ZoneMappings != nil {
		in, out := &in.ZoneMappings, &out.ZoneMappings
		*out = make([]ZoneMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBSpec.
func (in *NLBSpec) DeepCopy() *NLBSpec {
	if in == nil {
		return nil
	}
	out := new(NLBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out. In must be non-nil.
func (in *NLBStatus) DeepCopyInto(out *NLBStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBStatus.
func (in *NLBStatus) DeepCopy() *NLBStatus {
	if in == nil {
		return nil
	}
	out := new(NLBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out. In must be non-nil.
func (in *NLB) DeepCopyInto(out *NLB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLB.
func (in *NLB) DeepCopy() *NLB {
	if in == nil {
		return nil
	}
	out := new(NLB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NLB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out. In must be non-nil.
func (in *NLBList) DeepCopyInto(out *NLBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NLB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBList.
func (in *NLBList) DeepCopy() *NLBList {
	if in == nil {
		return nil
	}
	out := new(NLBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NLBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
