package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ServerGroupPhase represents the lifecycle phase of a ServerGroup CR.
type ServerGroupPhase string

const (
	ServerGroupPending ServerGroupPhase = "Pending"
	ServerGroupActive  ServerGroupPhase = "Active"
	ServerGroupFailed  ServerGroupPhase = "Failed"
)

// ServerGroupSpec defines the desired state of ServerGroup
type ServerGroupSpec struct {
	Region          string `json:"region"`
	VpcId           string `json:"vpcId"`
	ServerGroupName string `json:"serverGroupName"`
	// ServerGroupType: Ip | Instance
	ServerGroupType string `json:"serverGroupType"`
	// Protocol: TCP | UDP | TCPSSL
	Protocol  string `json:"protocol"`
	Scheduler string `json:"scheduler,omitempty"`
}

// ServerGroupStatus defines the observed state of ServerGroup
type ServerGroupStatus struct {
	Phase         ServerGroupPhase `json:"phase,omitempty"`
	ServerGroupId string           `json:"serverGroupId,omitempty"`
	Message       string           `json:"message,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// ServerGroup is the Schema for the servergroups API
type ServerGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ServerGroupSpec   `json:"spec,omitempty"`
	Status ServerGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerGroupList contains a list of ServerGroup
type ServerGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerGroup `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ServerGroup{}, &ServerGroupList{})
}

// DeepCopyInto copies all fields into out.
func (in *ServerGroupSpec) DeepCopyInto(out *ServerGroupSpec) { *out = *in }

// DeepCopy is an autogenerated deepcopy function.
func (in *ServerGroupSpec) DeepCopy() *ServerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ServerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *ServerGroupStatus) DeepCopyInto(out *ServerGroupStatus) { *out = *in }

// DeepCopy is an autogenerated deepcopy function.
func (in *ServerGroupStatus) DeepCopy() *ServerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ServerGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out.
func (in *ServerGroup) DeepCopyInto(out *ServerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ServerGroup) DeepCopy() *ServerGroup {
	if in == nil {
		return nil
	}
	out := new(ServerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ServerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields into out.
func (in *ServerGroupList) DeepCopyInto(out *ServerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		inItems, outItems := &in.Items, &out.Items
		*outItems = make([]ServerGroup, len(*inItems))
		for i := range *inItems {
			(*inItems)[i].DeepCopyInto(&(*outItems)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ServerGroupList) DeepCopy() *ServerGroupList {
	if in == nil {
		return nil
	}
	out := new(ServerGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ServerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
