//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all receiver into out. In must be non-nil.
func (in *NLBHealthCheckConfig) DeepCopyInto(out *NLBHealthCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBHealthCheckConfig.
func (in *NLBHealthCheckConfig) DeepCopy() *NLBHealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(NLBHealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver into out. In must be non-nil.
func (in *NLBPool) DeepCopyInto(out *NLBPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBPool.
func (in *NLBPool) DeepCopy() *NLBPool {
	if in == nil {
		return nil
	}
	out := new(NLBPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NLBPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all receiver into out. In must be non-nil.
func (in *NLBPoolList) DeepCopyInto(out *NLBPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NLBPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBPoolList.
func (in *NLBPoolList) DeepCopy() *NLBPoolList {
	if in == nil {
		return nil
	}
	out := new(NLBPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NLBPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all receiver into out. In must be non-nil.
func (in *NLBPoolSpec) DeepCopyInto(out *NLBPoolSpec) {
	*out = *in
	if in.BlockPorts != nil {
		in, out := &in.BlockPorts, &out.BlockPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]corev1.Protocol, len(*in))
		copy(*out, *in)
	}
	if in.EipIspTypes != nil {
		in, out := &in.EipIspTypes, &out.EipIspTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(NLBHealthCheckConfig)
		**out = **in
	}
	if in.SecurityProtectionTypes != nil {
		in, out := &in.SecurityProtectionTypes, &out.SecurityProtectionTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBPoolSpec.
func (in *NLBPoolSpec) DeepCopy() *NLBPoolSpec {
	if in == nil {
		return nil
	}
	out := new(NLBPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver into out. In must be non-nil.
func (in *NLBPoolStatus) DeepCopyInto(out *NLBPoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBPoolStatus.
func (in *NLBPoolStatus) DeepCopy() *NLBPoolStatus {
	if in == nil {
		return nil
	}
	out := new(NLBPoolStatus)
	in.DeepCopyInto(out)
	return out
}
